In [1]:
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
df = pd.read_html('/Users/garimajain/Desktop/GunLaws2015.html')

In [4]:
df1 = df[0]

In [6]:
df1.columns = ['Rank','State', 'State Laws Grade', 'Death Rate Per 100k', 'New Smart Gun Laws' ]

In [8]:
df1['Year'] = 2015

In [9]:
df1

,Rank,State,State Laws Grade,Death Rate Per 100k,New Smart Gun Laws,Year
0,1,California,A-,42,yes,2015
1,2,Connecticut,A-,47,yes,2015
2,3,New Jersey,A-,45,yes,2015
3,4,Maryland,A-,36,yes,2015
4,5,Massachusetts,A-,49,yes,2015
5,6,New York,A-,48,yes,2015
6,7,Hawaii,B+,50,yes,2015
7,8,Illinois,B+,40,yes,2015
8,9,Rhode Island,B+,46,yes,2015
9,10,Delaware,B,32,yes,2015
10,11,Washington,B-,39,yes,2015
11,12,Minnesota,C,43,NaN,2015
12,13,Pennsylvania,C,27,yes,2015
13,14,Oregon,C,28,yes,2015
14,15,Michigan,C,22,yes,2015
15,16,Colorado,C-,25,yes,2015
16,17,Iowa,C-,41,yes,2015
17,18,Wisconsin,D,35,NaN,2015
18,19,Ohio,D,29,NaN,2015
19,20,Virginia,D,33,NaN,2015
20,21,Nebraska,D,38,yes,2015
21,22,New Hampshire,D,44,NaN,2015
22,23,Indiana,D-,18,NaN,2015
23,24,West Virginia,D-,13,NaN,2015
24,25,Oklahoma,F,8,NaN,2015
25,25,North Carolina,F,21,yes,2015
26,27,Nevada,F,16,NaN,2015
27,28,South Carolina,F,11,NaN,2015
28,28,Georgia,F,20,NaN,2015
29,28,Florida,F,23,NaN,2015
30,28,North Dakota,F,24,NaN,2015
31,32,Tennessee,F,10,NaN,2015
32,33,New Mexico,F,9,NaN,2015
33,33,Texas,F,31,NaN,2015
34,35,Maine,F,30,NaN,2015
35,36,Alabama,F,4,NaN,2015
36,37,Montana,F,5,NaN,2015
37,37,Arkansas,F,6,NaN,2015
38,37,Utah,F,19,NaN,2015
39,40,South Dakota,F,34,NaN,2015
40,41,Missouri,F,12,NaN,2015
41,41,Vermont,F,37,NaN,2015
42,43,Kentucky,F,17,NaN,2015
43,44,Louisiana,F,2,NaN,2015
44,44,Idaho,F,14,NaN,2015
45,46,Alaska,F,1,NaN,2015
46,47,Arizona,F,15,NaN,2015
47,48,Wyoming,F,7,NaN,2015
48,49,Mississippi,F,3,NaN,2015
49,50,Kansas,F,26,NaN,2015

In [10]:
df1.to_csv('GunLaws_2015.csv', index=False, encoding='utf-8')