In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/garimajain/Desktop/Deceptive_Visualization/Deaths_by_gun_2015.csv')

In [4]:
del df['Operations']

In [6]:
del df['Address']

In [8]:
del df['City Or County']

In [13]:
Total_Killed = df['# Killed'].sum()

In [14]:
df.loc['Total_Killed'] = pd.Series(df['# Killed'].sum(), index = ['# Killed'])

In [16]:
Total_Injured = df['# Injured'].sum()

In [17]:
df.loc['Total_Injured'] = pd.Series(df['# Injured'].sum(), index = ['# Injured'])

In [35]:
df.columns.values['0'] = 'Incident Date'

/Users/garimajain/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':

In [38]:
df

                   Incident Date           State  # Killed  # Injured
0              December 31, 2015       Louisiana       0.0        6.0
1              December 27, 2015       Tennessee       0.0        4.0
2              December 26, 2015    Pennsylvania       0.0        4.0
3              December 25, 2015         Florida       0.0        4.0
4              December 25, 2015         Alabama       0.0        4.0
5              December 21, 2015      California       0.0        4.0
6              December 20, 2015  North Carolina       1.0        4.0
7              December 20, 2015         Florida       1.0        4.0
8              December 20, 2015         Florida       0.0        4.0
9              December 13, 2015      California       1.0        3.0
10             December 13, 2015      California       0.0        4.0
11             December 12, 2015         Georgia       0.0        4.0
12             December 12, 2015        Illinois       1.0        3.0
13             December 11, 2015        Maryland       1.0        3.0
14             December 11, 2015    Pennsylvania       0.0        4.0
15              December 8, 2015            Ohio       1.0        3.0
16              December 6, 2015       Louisiana       1.0        3.0
17              December 6, 2015        Nebraska       2.0        3.0
18              December 2, 2015      California      16.0       19.0
19              December 2, 2015         Georgia       1.0        3.0
20             November 29, 2015        Illinois       0.0        5.0
21             November 27, 2015        Colorado       3.0        9.0
22             November 27, 2015      California       2.0        2.0
23             November 24, 2015  South Carolina       0.0        4.0
24             November 23, 2015            Ohio       4.0        1.0
25             November 23, 2015       Minnesota       0.0        5.0
26             November 22, 2015           Texas       0.0        4.0
27             November 22, 2015      Washington       0.0        4.0
28             November 22, 2015        New York       0.0        5.0
29             November 22, 2015  South Carolina       1.0        3.0
...                          ...             ...       ...        ...
305             February 8, 2015       Tennessee       0.0        6.0
306             February 7, 2015         Georgia       5.0        2.0
307             February 6, 2015        Oklahoma       1.0        4.0
308             February 5, 2015            Ohio       3.0        3.0
309             February 1, 2015        New York       0.0        6.0
310             February 1, 2015        New York       1.0        4.0
311             January 31, 2015         Georgia       4.0        0.0
312             January 28, 2015         Georgia       1.0        3.0
313             January 26, 2015      California       1.0        3.0
314             January 24, 2015        New York       4.0        1.0
315             January 24, 2015        Nebraska       3.0        5.0
316             January 23, 2015   Massachusetts       0.0        6.0
317             January 20, 2015       Tennessee       1.0        3.0
318             January 19, 2015           Texas       2.0        5.0
319             January 13, 2015        Virginia       0.0        5.0
320             January 13, 2015        Illinois       2.0        2.0
321             January 11, 2015  North Carolina       2.0        5.0
322             January 11, 2015         Florida       1.0        3.0
323             January 11, 2015      California       0.0        5.0
324             January 10, 2015          Kansas       2.0        2.0
325              January 9, 2015      California       4.0        0.0
326              January 8, 2015   Massachusetts       1.0        3.0
327              January 7, 2015       Tennessee       1.0        3.0
328              January 6, 2015         Florida       1.0        3.0
329              January 4, 2015        Virginia       2.0        4.0
330              January 4, 2015           Texas       3.0        1.0
331              January 2, 2015         Georgia       1.0        4.0
332              January 1, 2015       Tennessee       0.0        5.0
Total_Killed                 NaN             NaN     367.0        NaN
Total_Injured                NaN             NaN       NaN     1327.0

[335 rows x 4 columns]

In [37]:
df.to_csv('shooting_2015.csv', index=False, encoding='utf-8')